# =====================================
# DCPrism - Main Docker Compose
# Orchestrateur principal avec composition modulaire
# Auteur : Inadvertance


# ============UTILISATION==============

## docker compose --profile $profile up -d ##

# Profiles disponibles : 
# --profile architecture - MariaDB, Redis,
# --profile orchestration -OpenTofu, Ansible  
# --profile tools - 
# --profile development - Adminer, Redis Commander, [todo] DBeaver
# --profile production - 
# [todo] monitoring - prometheus, grafana, loki, tempo
# [todo] logging - loki, promtail
# [todo] tracing - tempo, jaeger
# =====================================

# Inclusion des modules Docker

include:
  - lumiere/infra/docker/compose/core.compose.yml                 #
  - lumiere/infra/docker/compose/app/meniscus.compose.yml         #
  - lumiere/infra/docker/compose/app/fresnel.compose.yml          #
  - lumiere/infra/docker/compose/dev_tools.compose.yml            #
  - lumiere/infra/docker/compose/iac_tools.compose.yml            #

# Réseau commun

networks:
  lumieres-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1
