# =====================================
# DCPrism - Main Docker Compose
# Orchestrateur principal avec composition modulaire
# Auteur : Inadvertance


# ============UTILISATION==============

## docker compose --profile $profile up -d ##

# Profiles disponibles : 
# --profile dev - Application complète en développement (Traefik dev, app, worker, scheduler, MariaDB, Redis, outils dev)
# --profile prod - Application complète en production (Traefik prod avec SSL, app, worker, scheduler, MariaDB, Redis)
# =====================================

# Inclusion des modules Docker

include:
  - infra/docker/compose/core.compose.yml
  # Application unifiée DCPrism (Fresnel + Meniscus + Site vitrine)
  - infra/docker/compose/app/lumieres.compose.yml
  - infra/docker/compose/dev_tools.compose.yml
  - infra/docker/compose/iac_tools.compose.yml

# Réseau commun

networks:
  lumieres-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
          gateway: 172.30.0.1
