services:
  # =====================================
  # MENISCUS - DCParty (Event Management)
  # =====================================
  meniscus-app:
    build:
      context: ../../apps/meniscus
      dockerfile: docker/app/Dockerfile
      target: development
    container_name: dcprism-meniscus-app
    working_dir: /var/www
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=dichroic
      - DB_USERNAME=dichroic
      - DB_PASSWORD=dichroic_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis
    ports:
      - "8000:80"
      - "5174:5174"  # Vite dev server pour Meniscus
    volumes:
      - ../../apps/meniscus:/var/www
    depends_on:
      - mariadb
      - redis
    networks:
      - dcprism-network
    profiles:
      - meniscus
      - apps
      - prod
    restart: unless-stopped

  meniscus-worker:
    build:
      context: ../../apps/meniscus
      dockerfile: ../../infra/docker/backend/Dockerfile
    container_name: dcprism-meniscus-worker
    working_dir: /var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=dichroic
      - DB_USERNAME=dichroic
      - DB_PASSWORD=dichroic_password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_DRIVER=redis
      - QUEUE_CONNECTION=redis
    volumes:
      - ../../apps/meniscus:/var/www/html
    depends_on:
      - mariadb
      - redis
      - meniscus-app
    networks:
      - dcprism-network
    profiles:
      - meniscus
      - apps
      - workers
      - prod
    restart: unless-stopped
    command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600

# Le réseau sera défini dans le compose principal
