services:
  # =====================================
  # DEVELOPMENT TOOLS
  # =====================================
  mailpit:
    image: 'axllent/mailpit:latest'
    container_name: lumieres-mailpit
    restart: unless-stopped
    ports:
      - '1025:1025'  # SMTP port
      # - '8025:8025'  # Web UI port - Accès via Traefik uniquement
    networks:
      - lumieres-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mailpit.rule=Host(`localhost`) && PathPrefix(`/mailpit`)"
      - "traefik.http.routers.mailpit.entrypoints=web"
      - "traefik.http.services.mailpit.loadbalancer.server.port=8025"
      - "traefik.http.middlewares.mailpit-stripprefix.stripprefix.prefixes=/mailpit"
      - "traefik.http.routers.mailpit.middlewares=mailpit-stripprefix"
    profiles:
      - dev

  adminer:
    image: 'adminer:4.8.1'
    container_name: lumieres-adminer
    restart: unless-stopped
    # ports:
    #   - '8080:8080'  # Port désactivé - Accès via Traefik uniquement
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
    depends_on:
      - mariadb
    networks:
      - lumieres-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adminer.rule=Host(`localhost`) && PathPrefix(`/adminer`)"
      - "traefik.http.routers.adminer.entrypoints=web"
      - "traefik.http.services.adminer.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.adminer-stripprefix.stripprefix.prefixes=/adminer"
      - "traefik.http.routers.adminer.middlewares=adminer-stripprefix"
    profiles:
      - dev

  redis-commander:
    image: 'rediscommander/redis-commander:latest'
    container_name: lumieres-redis-commander
    restart: unless-stopped
    # ports:
    #   - '8081:8081'  # Port désactivé - Accès via Traefik uniquement
    environment:
      - 'REDIS_HOSTS=redis:redis:6379:0:redis_password'
    depends_on:
      - redis
    networks:
      - lumieres-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redis-commander.rule=Host(`localhost`) && PathPrefix(`/redis`)"
      - "traefik.http.routers.redis-commander.entrypoints=web"
      - "traefik.http.routers.redis-commander.priority=100"
      - "traefik.http.services.redis-commander.loadbalancer.server.port=8081"
      - "traefik.http.middlewares.redis-stripprefix.stripprefix.prefixes=/redis"
      - "traefik.http.routers.redis-commander.middlewares=redis-stripprefix"
    profiles:
      - dev

# Le réseau sera défini dans le compose principal
