# =============================================================================
# Configuration dynamique des middlewares Traefik
# =============================================================================

http:
  middlewares:
    # Sécurité headers
    security-headers:
      headers:
        accessControlAllowMethods:
          - GET
          - OPTIONS
          - PUT
          - POST
          - DELETE
          - PATCH
        accessControlMaxAge: 100
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        referrerPolicy: "same-origin"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          Server: ""
        sslProxyHeaders:
          X-Forwarded-Proto: https
        frameDeny: true
        contentTypeNosniff: true
        browserXssFilter: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 31536000
        stsPreload: true
        
    # Compression
    gzip:
      compress: {}
      
    # Rate limiting
    api-rate-limit:
      rateLimit:
        average: 100
        period: 1m
        burst: 50
        
    upload-rate-limit:
      rateLimit:
        average: 10
        period: 1m
        burst: 5
