services:
  # =====================================
  # DEVELOPMENT TOOLS
  # =====================================
  mailpit:
    image: 'axllent/mailpit:latest'
    container_name: lumieres-mailpit
    restart: unless-stopped
    ports:
      - '1025:1025'  # SMTP port
      - '8025:8025'  # Web UI port
    networks:
      - lumieres-network
    profiles:
      - dev

  adminer:
    image: 'adminer:4.8.1'
    container_name: lumieres-adminer
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
    depends_on:
      - mariadb
    networks:
      - lumieres-network
    profiles:
      - dev

  redis-commander:
    image: 'rediscommander/redis-commander:latest'
    container_name: lumieres-redis-commander
    restart: unless-stopped
    ports:
      - '8081:8081'
    environment:
      - 'REDIS_HOSTS=redis:redis:6379:0:redis_password'
    depends_on:
      - redis
    networks:
      - lumieres-network
    profiles:
      - dev

# Le réseau sera défini dans le compose principal
