# Configuration dynamique Traefik pour les assets statiques DCPrism

http:
  middlewares:
    # Cache pour assets statiques
    assets-headers:
      headers:
        customResponseHeaders:
          Cache-Control: "public, max-age=31536000, immutable"
          
    # Cache pour storage Laravel  
    storage-headers:
      headers:
        customResponseHeaders:
          Cache-Control: "public, max-age=2592000"

  routers:
    # Assets statiques avec cache long
    dcprism-assets:
      rule: "Host(`dcprism.local`) && PathPrefix(`/css`, `/js`, `/images`, `/assets`) || Host(`dcprism.local`) && Path(`/favicon.ico`)"
      service: dcprism-app
      middlewares:
        - assets-headers
        - gzip
      priority: 200
      tls:
        certResolver: letsencrypt

    # Storage Laravel avec cache moyen
    dcprism-storage:
      rule: "Host(`dcprism.local`) && PathPrefix(`/storage`)"
      service: dcprism-app  
      middlewares:
        - storage-headers
        - gzip
      priority: 150
      tls:
        certResolver: letsencrypt
